/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class ChatVisual extends javax.swing.JFrame {

    static String name;
    int port = 9500;
    String ip = "localhost";
    Client client;

    public ChatVisual(String name) {
        this.name = name;
        this.client = new Client(name,ip,port);
        client.init();
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelicon, "src/img/twitchbanner.png");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jlabelicon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        inciarSesionbtn = new javax.swing.JButton();
        inciarSesionbtn1 = new javax.swing.JButton();
        mensajeTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(180, 164, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(216, 207, 232));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 580, 280));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuarios Conectados");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 200, 30));

        jlabelicon.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jlabelicon.setForeground(new java.awt.Color(255, 255, 255));
        jlabelicon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 207, 232), 5));
        jPanel1.add(jlabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 580, 170));

        jTextArea3.setBackground(new java.awt.Color(216, 207, 232));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 270, 410));

        inciarSesionbtn.setBackground(new java.awt.Color(204, 204, 255));
        inciarSesionbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        inciarSesionbtn.setForeground(new java.awt.Color(123, 92, 180));
        inciarSesionbtn.setText("Enviar");
        jPanel1.add(inciarSesionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, -1, -1));

        inciarSesionbtn1.setBackground(new java.awt.Color(204, 204, 255));
        inciarSesionbtn1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        inciarSesionbtn1.setForeground(new java.awt.Color(123, 92, 180));
        inciarSesionbtn1.setText("Cerrar Sesion");
        jPanel1.add(inciarSesionbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, -1, -1));

        mensajeTxt.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jPanel1.add(mensajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 580, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatVisual(name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inciarSesionbtn;
    private javax.swing.JButton inciarSesionbtn1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel jlabelicon;
    private javax.swing.JTextField mensajeTxt;
    // End of variables declaration//GEN-END:variables
}
